# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BWkmXBaYdycGHrLRyRAmYqktSQKqigOz
"""

import streamlit as st
from retriever import generate_answers_from_communities
from util import load_pdf
import os

st.title("Paper Citation App")
st.write("Enter a query to search for paper citations from academic papers.")

query = st.text_input("Enter your search query:")

pdf_folder = "data/"
pdf_files = [f for f in os.listdir(pdf_folder) if f.endswith(".pdf")]

if pdf_files:
    st.write(f"**{len(pdf_files)} papers found** in the repository.")
else:
    st.write("**No PDF files found** in the repository.")

if query:
    st.write(f"Searching for papers related to: **{query}**")

    # Extract Text from PDFs
    documents = []
    for pdf in pdf_files:
        pdf_path = os.path.join(pdf_folder, pdf)
        text = load_pdf(pdf_path)
        documents.append(text)

    # Generate Citations
    citations = generate_answers_from_communities(documents, query)

    # Display Citation Results
    st.write("### Citation Results:")
    if citations:
        for idx, citation in enumerate(citations, 1):
            st.write(f"**{idx}.** {citation}")
    else:
        st.write("**No citations found for this query.** Try using different keywords.")